import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Play, RotateCcw } from 'lucide-react';
import EquationGraph from './EquationGraph';
import { InlineMath } from 'react-katex';

interface RLTrajectoryVisProps {
    formula?: string;
    label?: string;
    accent?: 'blue' | 'violet' | 'emerald' | 'red' | 'amber';
}

const TRAJECTORY = [
    { step: 0, s: 'Start', a: 'Move Right', r: '-', next: 'Pos1' },
    { step: 1, s: 'Pos1', a: 'Move Up', r: '-0.1', next: 'Pos2' },
    { step: 2, s: 'Pos2', a: 'Move Right', r: '-0.1', next: 'Pos3' },
    { step: 3, s: 'Pos3', a: 'Move Right', r: '+10', next: 'Goal!' },
];

export default function RLTrajectoryVis({
    formula = "\\tau = (s_0, a_0, r_1, s_1, a_1, r_2, s_2, \\dots, s_T)",
    label = 'RL Trajectory — Self-Generated Experience',
    accent = 'violet'
}: RLTrajectoryVisProps) {
    const [visibleSteps, setVisibleSteps] = useState(1);

    return (
        <EquationGraph
            formula={formula}
            label={label}
            accent={accent}
        >
            <div className="space-y-3">
                <div className="flex gap-2">
                    <button
                        onClick={() => setVisibleSteps(prev => Math.min(prev + 1, TRAJECTORY.length))}
                        disabled={visibleSteps >= TRAJECTORY.length}
                        className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium rounded-lg bg-violet-500 text-white hover:bg-violet-600 disabled:opacity-40"
                    >
                        <Play className="w-3 h-3" /> Step
                    </button>
                    <button onClick={() => setVisibleSteps(1)}
                        className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium rounded-lg bg-slate-200 dark:bg-slate-600 text-slate-700 dark:text-slate-300"
                    >
                        <RotateCcw className="w-3 h-3" /> Reset
                    </button>
                </div>
                <div className="flex items-center gap-1 overflow-x-auto pb-1">
                    {TRAJECTORY.slice(0, visibleSteps).map((t, i) => (
                        <React.Fragment key={i}>
                            <motion.div
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.3 }}
                                className="flex flex-col items-center min-w-[80px] p-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700"
                            >
                                <div className="text-[9px] text-slate-400"><InlineMath math={'s_{' + i + '}'} /></div>
                                <div className="text-xs font-bold text-slate-700 dark:text-slate-300">{t.s}</div>
                                <div className="text-[9px] text-amber-500 mt-0.5">
                                    <InlineMath math={'a_{' + i + '}'} />={t.a.split(' ')[0]}
                                </div>
                                {t.r !== '-' && (
                                    <div className="text-[9px] text-emerald-500">
                                        <InlineMath math={'r_{' + (i + 1) + '}'} />={t.r}
                                    </div>
                                )}
                            </motion.div>
                            {i < visibleSteps - 1 && (
                                <span className="text-xs text-slate-300 dark:text-slate-600">→</span>
                            )}
                        </React.Fragment>
                    ))}
                </div>
                <div className="p-2 rounded-lg bg-slate-50 dark:bg-slate-800/50 text-xs text-slate-500 dark:text-slate-400 font-mono">
                    τ = ({TRAJECTORY.slice(0, visibleSteps).map(t => `${t.s}, ${t.a.split(' ')[0]}${t.r !== '-' ? `, ${t.r}` : ''}`).join(', ')}{visibleSteps > 0 ? ', ...' : ''})
                </div>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                    A trajectory <InlineMath math="\\tau" /> is the sequence of states, actions, and rewards from one episode.
                    Unlike supervised learning, this data is generated by the agent's own actions — not provided by a teacher.
                </p>
            </div>
        </EquationGraph>
    );
}
