import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Play, Pause, RotateCcw, ChevronRight, Gauge, Settings2,
    Info, Download, TrendingUp, Cpu, X, BookOpen, Terminal, Trophy,
    FileSpreadsheet, Sparkles, CheckCircle, HelpCircle, Send
} from 'lucide-react';

export interface LabTelemetry {
    label: string;
    value: string | number;
    unit?: string;
    color?: string;
    highlight?: boolean;
}

export interface LabChallenge {
    id: string;
    quest: string;
    target: string;
    isCompleted: boolean;
}

export interface NotebookEntry {
    task: string;
    question: string;
    hint?: string;
}

interface VirtualLabShellProps {
    title: string;
    description: string;
    objective: string;
    controls?: React.ReactNode;
    telemetry?: LabTelemetry[];
    children: React.ReactNode;
    onReset?: () => void;
    onStep?: () => void;
    onToggleRun?: () => void;
    isRunning?: boolean;
    speed?: number;
    onSpeedChange?: (v: number) => void;
    showStepBtn?: boolean;
    tips?: string[];
    badge?: string;
    
    // NEW EXPERIENTIAL PROPS
    challenges?: LabChallenge[];
    logs?: string[];
    notebook?: NotebookEntry[];
    onDownloadReport?: () => void;
}

export default function VirtualLabShell({
    title, description, objective, controls, telemetry = [],
    children, onReset, onStep, onToggleRun, isRunning = false,
    speed = 1, onSpeedChange, showStepBtn = true, tips = [], badge,
    challenges = [], logs = [], notebook = [], onDownloadReport
}: VirtualLabShellProps) {
    const [activeTab, setActiveTab] = useState<'simulation' | 'notebook' | 'terminal' | 'quests'>('simulation');
    const [showTips, setShowTips] = useState(false);
    const [showSettings, setShowSettings] = useState(false);
    
    // Interactive Worksheet answers state
    const [answers, setAnswers] = useState<Record<number, string>>({});
    const [validated, setValidated] = useState<Record<number, boolean>>({});
    
    const consoleEndRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (activeTab === 'terminal' && consoleEndRef.current) {
            consoleEndRef.current.scrollIntoView({ behavior: 'smooth' });
        }
    }, [logs, activeTab]);

    const handleValidate = (index: number) => {
        if (!answers[index]?.trim()) return;
        setValidated(prev => ({ ...prev, [index]: true }));
    };

    const triggerReportDownload = () => {
        if (onDownloadReport) {
            onDownloadReport();
            return;
        }

        // Default export lab report
        const reportContent = `
=========================================
🔬 VIRTUAL LAB REPORT: ${title.toUpperCase()}
=========================================
Date: ${new Date().toLocaleString()}
Objective: ${objective}

-----------------------------------------
📊 EXPERIMENT TELEMETRY
-----------------------------------------
${telemetry.map(t => `${t.label}: ${t.value} ${t.unit || ''}`).join('\n')}

-----------------------------------------
📓 GUIDED WORKSHEET ANSWERS
-----------------------------------------
${notebook.length > 0 ? notebook.map((n, i) => `
Task ${i + 1}: ${n.task}
Question: ${n.question}
Student Observation: ${answers[i] || 'No response recorded.'}
Validated: ${validated[i] ? 'Yes' : 'No'}
`).join('\n') : 'No guided notebook was configured for this lab.'}

-----------------------------------------
🏆 CHALLENGES COMPLETED
-----------------------------------------
${challenges.length > 0 ? challenges.map(c => `[${c.isCompleted ? '✓' : ' '}] ${c.quest} (${c.target})`).join('\n') : 'No challenges configured.'}

=========================================
Generated by RLIS Experiential Learning platform.
=========================================
        `.trim();

        const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_lab_report.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    // Calculate quest progress
    const completedQuests = challenges.filter(c => c.isCompleted).length;
    const totalQuests = challenges.length;
    const progressPercent = totalQuests > 0 ? (completedQuests / totalQuests) * 100 : 0;

    return (
        <div className="rounded-3xl border-2 border-cyan-200 dark:border-cyan-900/50 bg-gradient-to-br from-slate-50 to-slate-100/90 dark:from-slate-900 dark:to-slate-950 overflow-hidden shadow-2xl transition-all">
            
            {/* Lab Header Bar */}
            <div className="bg-slate-950 px-6 py-4 flex items-center justify-between gap-4 flex-wrap border-b border-slate-800">
                <div className="flex items-center gap-3">
                    <div className="flex gap-1.5">
                        <div className="w-3.5 h-3.5 rounded-full bg-red-500 shadow-lg shadow-red-500/20" />
                        <div className="w-3.5 h-3.5 rounded-full bg-amber-400 shadow-lg shadow-amber-400/20" />
                        <div className="w-3.5 h-3.5 rounded-full bg-emerald-500 shadow-lg shadow-emerald-500/20" />
                    </div>
                    <div>
                        <div className="flex items-center gap-2">
                            <span className="text-white font-black text-sm tracking-wide flex items-center gap-1.5">
                                <Sparkles size={16} className="text-cyan-400" />
                                {title}
                            </span>
                            {badge && (
                                <span className="px-2.5 py-0.5 text-[8px] font-black bg-cyan-500/10 text-cyan-400 rounded-full uppercase tracking-widest border border-cyan-500/30">
                                    {badge}
                                </span>
                            )}
                        </div>
                        <span className="text-slate-400 text-[10px] font-medium">{description}</span>
                    </div>
                </div>

                {/* Header Controls */}
                <div className="flex items-center gap-2">
                    {tips.length > 0 && (
                        <button
                            onClick={() => setShowTips(t => !t)}
                            className={`p-2.5 rounded-xl transition-all border ${showTips ? 'bg-amber-500/20 text-amber-400 border-amber-500/30' : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-amber-400'}`}
                            title="Lab Tips"
                        >
                            <Info size={14} />
                        </button>
                    )}
                    {onSpeedChange && (
                        <button
                            onClick={() => setShowSettings(s => !s)}
                            className={`p-2.5 rounded-xl transition-all border ${showSettings ? 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30' : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-indigo-400'}`}
                            title="Settings"
                        >
                            <Settings2 size={14} />
                        </button>
                    )}
                    <button
                        onClick={triggerReportDownload}
                        className="p-2.5 bg-slate-900 text-slate-400 border border-slate-800 rounded-xl hover:text-white hover:border-slate-700 transition-all flex items-center gap-1.5 text-xs font-bold"
                        title="Download Report"
                    >
                        <Download size={14} />
                        <span className="hidden sm:inline">Export</span>
                    </button>
                    {onReset && (
                        <button
                            onClick={onReset}
                            className="p-2.5 bg-slate-900 text-slate-400 border border-slate-800 rounded-xl hover:text-red-400 hover:border-red-500/30 transition-all"
                            title="Reset Lab"
                        >
                            <RotateCcw size={14} />
                        </button>
                    )}
                </div>
            </div>

            {/* Navigation Tabs */}
            <div className="flex bg-slate-950/80 backdrop-blur-md px-6 py-2 border-b border-slate-900/50 gap-2 overflow-x-auto">
                <button
                    onClick={() => setActiveTab('simulation')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 ${activeTab === 'simulation' ? 'bg-slate-800 text-cyan-400 shadow-md' : 'text-slate-400 hover:bg-slate-900'}`}
                >
                    <Cpu size={14} />
                    Simulation Sandbox
                </button>
                <button
                    onClick={() => setActiveTab('notebook')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 relative ${activeTab === 'notebook' ? 'bg-slate-800 text-cyan-400 shadow-md' : 'text-slate-400 hover:bg-slate-900'}`}
                >
                    <BookOpen size={14} />
                    Guided Notebook
                    {notebook.length > 0 && (
                        <span className="absolute -top-1 -right-1 w-4 h-4 bg-cyan-500 text-slate-950 font-black rounded-full flex items-center justify-center text-[8px]">
                            {notebook.length}
                        </span>
                    )}
                </button>
                <button
                    onClick={() => setActiveTab('terminal')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 ${activeTab === 'terminal' ? 'bg-slate-800 text-cyan-400 shadow-md' : 'text-slate-400 hover:bg-slate-900'}`}
                >
                    <Terminal size={14} />
                    Lab Console
                    {logs.length > 0 && (
                        <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse" />
                    )}
                </button>
                <button
                    onClick={() => setActiveTab('quests')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 relative ${activeTab === 'quests' ? 'bg-slate-800 text-cyan-400 shadow-md' : 'text-slate-400 hover:bg-slate-900'}`}
                >
                    <Trophy size={14} />
                    Quest Board
                    {totalQuests > 0 && (
                        <span className="px-1.5 py-0.5 text-[8px] bg-amber-500 text-slate-950 font-black rounded-full leading-none">
                            {completedQuests}/{totalQuests}
                        </span>
                    )}
                </button>
            </div>

            {/* Tips Panel */}
            <AnimatePresence>
                {showTips && tips.length > 0 && (
                    <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="bg-amber-50 dark:bg-amber-950/20 border-b border-amber-100 dark:border-amber-900/30 overflow-hidden"
                    >
                        <div className="px-6 py-4 flex items-start gap-3">
                            <Info size={18} className="text-amber-500 mt-0.5 flex-shrink-0" />
                            <div className="space-y-1">
                                <p className="text-xs font-black text-amber-800 dark:text-amber-300 uppercase tracking-widest">Lab Tips & Observations</p>
                                <ul className="space-y-1">
                                    {tips.map((tip, i) => (
                                        <li key={i} className="text-xs text-amber-700 dark:text-amber-400 flex gap-2">
                                            <span className="text-amber-500 font-bold">→</span> {tip}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                            <button onClick={() => setShowTips(false)} className="ml-auto p-1 text-amber-400 hover:text-amber-600 rounded-lg">
                                <X size={16} />
                            </button>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Settings Panel */}
            <AnimatePresence>
                {showSettings && onSpeedChange && (
                    <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="bg-indigo-50 dark:bg-indigo-950/20 border-b border-indigo-100 dark:border-indigo-900/30 overflow-hidden"
                    >
                        <div className="px-6 py-4 flex items-center gap-6 flex-wrap">
                            <div className="flex items-center gap-3">
                                <Gauge size={16} className="text-indigo-500" />
                                <span className="text-xs font-bold text-indigo-800 dark:text-indigo-300">Simulation Speed</span>
                                <input
                                    type="range" min={0.5} max={5} step={0.5} value={speed}
                                    onChange={e => onSpeedChange(parseFloat(e.target.value))}
                                    className="w-28 accent-indigo-600"
                                />
                                <span className="text-xs font-black text-indigo-600 w-8">{speed}×</span>
                            </div>
                            {controls}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Objective Banner */}
            <div className="px-6 py-3.5 bg-cyan-900/5 dark:bg-cyan-950/20 border-b border-cyan-100 dark:border-cyan-950/30">
                <div className="flex items-center gap-2.5">
                    <TrendingUp size={14} className="text-cyan-500 flex-shrink-0" />
                    <p className="text-xs font-medium text-slate-700 dark:text-slate-300">
                        <span className="font-black text-cyan-700 dark:text-cyan-400 uppercase tracking-wider text-[10px] mr-1.5">Objective</span>
                        {objective}
                    </p>
                </div>
            </div>

            {/* Main Tabs Canvas Area */}
            <div className="p-6">
                <AnimatePresence mode="wait">
                    {activeTab === 'simulation' && (
                        <motion.div
                            key="simulation"
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -10 }}
                        >
                            {children}
                        </motion.div>
                    )}

                    {activeTab === 'notebook' && (
                        <motion.div
                            key="notebook"
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -10 }}
                            className="space-y-6"
                        >
                            <div className="flex items-center gap-2 mb-2">
                                <BookOpen className="text-cyan-500" size={18} />
                                <h4 className="font-bold text-slate-800 dark:text-white">Guided Experiment Workbook</h4>
                            </div>
                            
                            {notebook.length > 0 ? (
                                <div className="space-y-4">
                                    {notebook.map((entry, index) => (
                                        <div key={index} className="p-5 rounded-2xl bg-white dark:bg-slate-800 border border-slate-100 dark:border-slate-700 shadow-sm space-y-4">
                                            <div className="flex justify-between items-start gap-4">
                                                <div className="space-y-1">
                                                    <span className="px-2 py-0.5 bg-cyan-100 dark:bg-cyan-950 text-cyan-700 dark:text-cyan-400 text-[10px] font-black rounded-lg uppercase tracking-wider">
                                                        Task {index + 1}
                                                    </span>
                                                    <p className="text-xs font-black text-slate-800 dark:text-slate-200">{entry.task}</p>
                                                </div>
                                                {validated[index] && (
                                                    <span className="flex items-center gap-1 text-[10px] font-bold text-emerald-500">
                                                        <CheckCircle size={14} />
                                                        Validated
                                                    </span>
                                                )}
                                            </div>

                                            <div className="p-3 bg-slate-50 dark:bg-slate-900 rounded-xl border border-slate-100 dark:border-slate-800/80">
                                                <p className="text-xs text-slate-600 dark:text-slate-400 font-medium italic">
                                                    ❓ <span className="font-bold">Observation Question: </span>{entry.question}
                                                </p>
                                            </div>

                                            {entry.hint && (
                                                <div className="flex items-center gap-1.5 text-[10px] text-amber-500 font-bold">
                                                    <HelpCircle size={12} />
                                                    <span>Hint: {entry.hint}</span>
                                                </div>
                                            )}

                                            <div className="flex gap-2">
                                                <textarea
                                                    disabled={validated[index]}
                                                    value={answers[index] || ''}
                                                    onChange={e => setAnswers(prev => ({ ...prev, [index]: e.target.value }))}
                                                    placeholder="Record your observations here based on the simulation run..."
                                                    className="flex-1 p-3 text-xs bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-850 rounded-xl focus:outline-none focus:border-cyan-500 disabled:opacity-60 resize-none h-20"
                                                />
                                                <button
                                                    disabled={validated[index] || !answers[index]?.trim()}
                                                    onClick={() => handleValidate(index)}
                                                    className="self-end px-4 py-3 bg-cyan-500 hover:bg-cyan-600 text-slate-950 rounded-xl font-bold text-xs flex items-center gap-1.5 transition-colors disabled:opacity-50"
                                                >
                                                    <Send size={12} />
                                                    Submit
                                                </button>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div className="text-center py-12 bg-white dark:bg-slate-800 rounded-3xl border border-slate-100 dark:border-slate-700 space-y-3">
                                    <BookOpen size={36} className="mx-auto text-slate-300" />
                                    <p className="text-xs text-slate-500 font-bold">No guided exercises configured for this lab.</p>
                                </div>
                            )}
                        </motion.div>
                    )}

                    {activeTab === 'terminal' && (
                        <motion.div
                            key="terminal"
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -10 }}
                            className="space-y-4"
                        >
                            <div className="flex justify-between items-center mb-1">
                                <div className="flex items-center gap-2">
                                    <Terminal className="text-cyan-500" size={18} />
                                    <h4 className="font-bold text-slate-800 dark:text-white">Lab Console Log</h4>
                                </div>
                                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Real-time Stream</span>
                            </div>

                            <div className="bg-slate-950 rounded-2xl border border-slate-800 p-4 font-mono text-xs text-cyan-400 overflow-y-auto h-72 space-y-2 shadow-inner">
                                {logs.length > 0 ? (
                                    logs.map((log, i) => (
                                        <div key={i} className="flex gap-2 items-start hover:bg-slate-900/50 py-0.5 px-1 rounded transition-colors">
                                            <span className="text-slate-600 select-none">[{i + 1}]</span>
                                            <span className="text-slate-400 select-none">&gt;</span>
                                            <span className="leading-relaxed whitespace-pre-wrap">{log}</span>
                                        </div>
                                    ))
                                ) : (
                                    <div className="text-slate-500 text-center py-20 flex flex-col items-center justify-center gap-2">
                                        <Terminal size={24} className="animate-pulse" />
                                        <span>Console is empty. Start the simulation to stream logs...</span>
                                    </div>
                                )}
                                <div ref={consoleEndRef} />
                            </div>
                        </motion.div>
                    )}

                    {activeTab === 'quests' && (
                        <motion.div
                            key="quests"
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -10 }}
                            className="space-y-6"
                        >
                            <div className="flex items-center justify-between gap-4">
                                <div className="flex items-center gap-2">
                                    <Trophy className="text-amber-500" size={18} />
                                    <h4 className="font-bold text-slate-800 dark:text-white">Active Achievements & Quests</h4>
                                </div>
                                <span className="text-xs font-black text-amber-500">🏆 {completedQuests} / {totalQuests} Complete</span>
                            </div>

                            {totalQuests > 0 && (
                                <div className="space-y-2">
                                    <div className="flex justify-between items-center text-[10px] font-black uppercase text-slate-500">
                                        <span>Completion Progress</span>
                                        <span>{progressPercent.toFixed(0)}%</span>
                                    </div>
                                    <div className="w-full h-3 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden border border-slate-200 dark:border-slate-700">
                                        <motion.div
                                            className="h-full bg-gradient-to-r from-amber-400 to-yellow-500"
                                            initial={{ width: 0 }}
                                            animate={{ width: `${progressPercent}%` }}
                                            transition={{ duration: 0.5 }}
                                        />
                                    </div>
                                </div>
                            )}

                            {challenges.length > 0 ? (
                                <div className="grid sm:grid-cols-2 gap-4">
                                    {challenges.map((c, i) => (
                                        <div
                                            key={c.id}
                                            className={`p-5 rounded-2xl border transition-all flex items-start gap-4 shadow-sm ${c.isCompleted ? 'bg-emerald-50/50 dark:bg-emerald-950/10 border-emerald-200 dark:border-emerald-900/30' : 'bg-white dark:bg-slate-800 border-slate-100 dark:border-slate-700'}`}
                                        >
                                            <div className={`p-2.5 rounded-xl ${c.isCompleted ? 'bg-emerald-500 text-slate-950' : 'bg-slate-100 dark:bg-slate-700 text-slate-400'}`}>
                                                <Trophy size={18} className={c.isCompleted ? 'animate-bounce' : ''} />
                                            </div>
                                            <div className="space-y-1">
                                                <h5 className={`text-xs font-black ${c.isCompleted ? 'text-emerald-900 dark:text-emerald-300' : 'text-slate-800 dark:text-slate-200'}`}>{c.quest}</h5>
                                                <span className="text-[10px] text-slate-400 font-bold block">Target: {c.target}</span>
                                            </div>
                                            {c.isCompleted && (
                                                <span className="ml-auto px-2 py-0.5 bg-emerald-500 text-slate-950 text-[9px] font-black rounded-lg uppercase tracking-wider flex items-center gap-0.5">
                                                    <CheckCircle size={10} />
                                                    Unlocked
                                                </span>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div className="text-center py-12 bg-white dark:bg-slate-800 rounded-3xl border border-slate-100 dark:border-slate-700 space-y-3">
                                    <Trophy size={36} className="mx-auto text-slate-300" />
                                    <p className="text-xs text-slate-500 font-bold">No quests configured for this lab.</p>
                                </div>
                            )}
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            {/* Telemetry Bar */}
            {telemetry.length > 0 && (
                <div className="px-6 py-4 bg-slate-950 border-t border-slate-900 flex gap-6 flex-wrap items-center">
                    <div className="flex items-center gap-1.5 text-slate-400">
                        <Cpu size={12} className="text-cyan-400 animate-pulse" />
                        <span className="text-[9px] font-black uppercase tracking-widest">Telemetry</span>
                    </div>
                    <div className="flex gap-6 flex-wrap">
                        {telemetry.map((t, i) => (
                            <div key={i} className="flex items-center gap-2">
                                <span className="text-[10px] text-slate-500 font-bold">{t.label}:</span>
                                <span
                                    className={`text-xs font-black font-mono tracking-wide ${t.highlight ? 'text-emerald-400' : t.color || 'text-slate-100'}`}
                                >
                                    {typeof t.value === 'number' ? t.value.toFixed(2) : t.value}
                                    {t.unit && <span className="text-slate-500 text-[9px] ml-0.5 font-sans font-bold">{t.unit}</span>}
                                </span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Action Footer */}
            {(onToggleRun || onStep) && (
                <div className="px-6 py-4 bg-slate-950 border-t border-slate-900 flex items-center gap-3">
                    {onToggleRun && (
                        <button
                            onClick={onToggleRun}
                            className={`flex items-center gap-2 px-6 py-3 rounded-xl font-black text-xs uppercase tracking-wider transition-all shadow-md active:scale-95 ${
                                isRunning
                                    ? 'bg-red-500/20 text-red-400 border border-red-500/30 hover:bg-red-500/30 shadow-red-500/5'
                                    : 'bg-emerald-500 text-slate-950 hover:bg-emerald-400 shadow-emerald-500/10'
                            }`}
                        >
                            {isRunning ? <><Pause size={14} /> Pause Simulation</> : <><Play size={14} /> Run Simulation</>}
                        </button>
                    )}
                    {showStepBtn && onStep && !isRunning && (
                        <button
                            onClick={onStep}
                            className="flex items-center gap-2 px-5 py-3 rounded-xl font-black text-xs uppercase tracking-wider bg-slate-800 text-slate-200 border border-slate-750 hover:bg-slate-700 transition-all active:scale-95"
                        >
                            <ChevronRight size={14} /> Step
                        </button>
                    )}
                    {onReset && (
                        <button
                            onClick={onReset}
                            className="flex items-center gap-2 px-4 py-3 rounded-xl font-bold text-xs bg-slate-900 text-slate-400 border border-slate-800 hover:text-red-400 hover:border-red-500/30 transition-all active:scale-95 ml-auto"
                        >
                            <RotateCcw size={12} /> Reset
                        </button>
                    )}
                </div>
            )}
        </div>
    );
}
